USE DATABASE PD_INTEL;
CREATE VIEW V_SALES_ORDER_HEADER AS
SELECT 
    o.ORDER_ID, 
    o.ORDER_DATE, 
    o.STATUS, 
    o.CUSTOMER_ID, 
    o.ITEM_COUNT, 
    o.TOTAL_AMOUNT, 
    o.DISCOUNT, 
    (o.TOTAL_AMOUNT - o.DISCOUNT) AS FINAL_INVOICE_AMT
FROM 
    ORDER_BASE.T_SALES_ORDER_HEADER o
JOIN 
    ORDER_BASE.T_CUSTOMER c ON o.CUSTOMER_ID = c.CUSTOMER_ID
WHERE 
    o.STATUS = 'Active';
    
