CREATE OR REPLACE PROCEDURE P_ROOT_CORE_BUILD()
RETURNS STRING
LANGUAGE SQL
AS
$$

BEGIN
    -- Load data into T_COMPRESS_BOM_CORE
    BEGIN
        INSERT INTO BMATHUB_BASE.T_COMPRESS_BOM_CORE (INPUT_ITEM_ID, ITEM_CLASS_NM, OUTPUT_ITEM_ID, BOM_NUM, LOCATION)
        SELECT
        ob.INPUT_ITEM_ID,
        ob.ITEM_CLASS_NM,
        ob.OUTPUT_ITEM_ID,
        ROW_NUMBER() OVER (ORDER BY ob.INPUT_ITEM_ID) + 100 AS BOM_NUM,  -- Adjust to start from 101
        COALESCE(
            CASE
                WHEN ob.ITEM_CLASS_NM IN ('DIEPREP', 'IC') THEN tmr.LOCATION
                ELSE ob.LOCATION
            END,
            ob.LOCATION
        ) AS LOCATION
    FROM BMATHUB_BASE.T_ORIG_BOM ob
    JOIN BMATHUB_BASE.T_ITEM_DETAIL_ROOT idr
        ON ob.INPUT_ITEM_ID = idr.ITEM_ID
    JOIN BMATHUB_BASE.T_LOCATION_ROOT lr
        ON ob.INPUT_ITEM_ID = lr.ITEM_ID AND ob.ITEM_CLASS_NM = lr.ITEM_CLASS_NM
    LEFT JOIN BMATHUB_BASE.T_METADATA_RULES tmr
        ON ob.ITEM_CLASS_NM = tmr.ITEM_CLASS_NM;
                                          
END;
END;
$$;