 USE DATABASE PD_INTEL;
CREATE SCHEMA PD_INTEL.ORDER_BASE
COMMENT = 'Consists of Base table, Functions and SPs';

CREATE SCHEMA PD_INTEL.ORDER_XFRM
COMMENT = 'Contains of Views for Xfrm';

CREATE SCHEMA PD_INTEL.ORDER_ANALYSIS
COMMENT = 'Consumption View for Outside App'
