USE DATABASE PD_INTEL;
CREATE OR REPLACE TABLE ORDER_BASE.T_SALES_ORDER_HEADER 
(	
    ORDER_ID	VARCHAR(10),
    ORDER_DATE	DATE,
    STATUS	VARCHAR(10),
    CUSTOMER_ID	VARCHAR(10),
    ITEM_COUNT	INT,
    TOTAL_AMOUNT	NUMBER(12,2),
    DISCOUNT	NUMBER(10,2),
    COUPON_CODE VARCHAR(20),
    CREATE_DATE	DATE,
    CREATE_USER	VARCHAR(10)
);
