USE DATABASE PD_INTEL;

 CREATE or replace VIEW V_CUSTOMER AS
SELECT 
    c.CUSTOMER_ID,
    c.ADDRESS,
    c.PHONE_NO,
    c.CATEGORY,
    c.STATUS,
    COALESCE(o.TOTAL_ORDERS, 0) AS TOTAL_ORDERS,
    COALESCE(o.TOTAL_INVOICE_AMOUNT, 0) AS TOTAL_INVOICE_AMOUNT,
    c.LOYALTY_POINTS
FROM 
    ORDER_BASE.T_CUSTOMER c
LEFT JOIN (
    SELECT 
        CUSTOMER_ID,
        COUNT(ORDER_ID) AS TOTAL_ORDERS,
        SUM(FINAL_INVOICE_AMT) AS TOTAL_INVOICE_AMOUNT
    FROM 
        ORDER_BASE.T_SALES_ORDER_HEADER
    GROUP BY 
        CUSTOMER_ID
) o ON c.CUSTOMER_ID = o.CUSTOMER_ID;