USE DATABASE PD_INTEL;

CREATE or REPLACE VIEW V_PROMOTION AS
SELECT
    c.CUSTOMER_ID,
    c.CATEGORY AS CUSTOMER_CATEGORY,
    so.COUPON_CODE AS PROMOTION_TYPE,
    p.PROMOTION_VALUE,
    p.COMMENT
    
FROM
    ORDER_BASE.T_SALES_ORDER_HEADER so
JOIN
    ORDER_BASE.T_CUSTOMER c ON so.CUSTOMER_ID = c.CUSTOMER_ID
JOIN
    ORDER_BASE.T_PROMOTION p ON c.CATEGORY = p.CUSTOMER_CATEGORY
    AND so.COUPON_CODE = p.PROMOTION_TYPE ;