USE DATABASE PD_INTEL;

CREATE or replace VIEW V_SALES_ORDER_DETAIL AS
SELECT 
    ORDER_ID,
    ORDER_DATE,
    CUSTOMER_ID,
    ITEM_ID,
    QTY,
    TOTAL_AMOUNT
FROM 
    ORDER_BASE.T_SALES_ORDER_DETAIL;
    
   