USE DATABASE PD_INTEL;
CREATE OR REPLACE TABLE BMATHUB_BASE.T_COMPRESS_BOM_CORE
(
    INPUT_ITEM_ID	VARCHAR(21),
    ITEM_CLASS_NM	VARCHAR(30),
    OUTPUT_ITEM_ID	VARCHAR(30),
    BOM_NUM         NUMBER(12,2),
    LOCATION        VARCHAR(10),
    CREATE_DATE     DATE,
    CREATE_USER     VARCHAR(30)
);